import "./globals.css";
import { Inter } from "next/font/google";
import { api } from "./api";
import { HeaderNavigation } from "./ui/headerNavigation";
import { Footer } from "./ui/footer";
import { Sidebar } from "./ui/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Preload data
  await api.preloadData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <HeaderNavigation />
          <div>
            <Sidebar />
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
